"""Add trade_transaction_type column

Revision ID: b09cedc0aa2d
Revises: 
Create Date: 2024-04-21 00:38:22.918615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09cedc0aa2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_table', sa.Column('trade_transaction_type', sa.String(), nullable=True))
    # op.drop_index('ix_bank_details_id', table_name='bank_details')
    # op.drop_table('bank_details')
    # op.drop_table('transactions')
    # op.drop_table('account')
    # op.drop_index('ix_trade_table_id', table_name='trade_table')
    # op.drop_table('trade_table')
    # op.drop_table('assets_pair')
    # op.drop_table('card_details')
    # op.drop_index('ix_users_email', table_name='users')
    # op.drop_table('users')
    # op.drop_table('crm_user_base')
    # op.drop_index('ix_crypto_currency_withdraw_id', table_name='crypto_currency_withdraw')
    # op.drop_index('ix_crypto_currency_withdraw_wallet_address', table_name='crypto_currency_withdraw')
    # op.drop_table('crypto_currency_withdraw')
    # op.drop_index('ix_crypto_currency_wallet_id', table_name='crypto_currency_wallet')
    # op.drop_index('ix_crypto_currency_wallet_wallet_address', table_name='crypto_currency_wallet')
    # op.drop_table('crypto_currency_wallet')
    # op.drop_table('crm_user_activities')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_user_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['crm_user_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_currency_wallet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(), nullable=True),
    sa.Column('network_chain', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_token', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crypto_currency_wallet_wallet_address', 'crypto_currency_wallet', ['wallet_address'], unique=1)
    op.create_index('ix_crypto_currency_wallet_id', 'crypto_currency_wallet', ['id'], unique=False)
    op.create_table('crypto_currency_withdraw',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(), nullable=True),
    sa.Column('network_chain', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_token', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crypto_currency_withdraw_wallet_address', 'crypto_currency_withdraw', ['wallet_address'], unique=1)
    op.create_index('ix_crypto_currency_withdraw_id', 'crypto_currency_withdraw', ['id'], unique=False)
    op.create_table('crm_user_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('status_type_enum', sa.VARCHAR(length=14), nullable=True),
    sa.Column('activated', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('user_type_enum', sa.VARCHAR(length=11), nullable=True),
    sa.Column('can_auto_trade', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('card_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(), nullable=True),
    sa.Column('lastname', sa.VARCHAR(), nullable=True),
    sa.Column('card_number', sa.INTEGER(), nullable=True),
    sa.Column('expiry_date', sa.VARCHAR(), nullable=True),
    sa.Column('cvv', sa.INTEGER(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_pair',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asset_pair', sa.VARCHAR(), nullable=True),
    sa.Column('asset_url', sa.VARCHAR(), nullable=True),
    sa.Column('asset_type_enum', sa.VARCHAR(length=14), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('asset_pair_type', sa.VARCHAR(), nullable=True),
    sa.Column('trade_type_enum', sa.VARCHAR(length=6), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('profit', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_table_id', 'trade_table', ['id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('account_type_enum', sa.VARCHAR(length=8), nullable=True),
    sa.Column('main_balance', sa.INTEGER(), nullable=True),
    sa.Column('referral_balance', sa.INTEGER(), nullable=True),
    sa.Column('bonus_balance', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('transaction_type_enum', sa.VARCHAR(length=8), nullable=False),
    sa.Column('transaction_amount', sa.INTEGER(), nullable=True),
    sa.Column('transaction_method_enum', sa.VARCHAR(length=14), nullable=False),
    sa.Column('status_enum', sa.VARCHAR(length=12), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), nullable=True),
    sa.Column('account_name', sa.VARCHAR(), nullable=True),
    sa.Column('iban', sa.VARCHAR(), nullable=True),
    sa.Column('bic', sa.VARCHAR(), nullable=True),
    sa.Column('reference', sa.VARCHAR(), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_details_id', 'bank_details', ['id'], unique=False)
    # ### end Alembic commands ###
